### ISSUE TITLE
hocinebendou/b3a.biobank repo does not exist currently

### ISSUE THREAD

**Issue by dnk8n** [SANBI-SA/baobab.lims.docker#2]
Repo, https://github.com/hocinebendou/b3a.biobank.git , referenced in the main Dockerfile does not exist currently. Has it been renamed?

**Comment by thobalose** [comment]
@dnk8n Yes, the repo has been moved to https://github.com/BaobabLims/baobab.lims.

To test out using docker run: `docker run -p 8080:8080 quay.io/baobab-lims/baobab-lims` and follow instructions on the above mentioned repo.

Thank you.

**Comment by thobalose** [comment]
@dnk8n I am closing issue. 

Hope you found the above comment helpful.

**Comment by dnk8n** [comment]
@thobalose This issue relates to this repo, which is currently broken. So in my view the issue still stands and should be open until one of the following is done:

- Some documentation is added telling new visitors of the repo that this is deprecated and to please visit the [current implementation](https://github.com/BaobabLims/baobab.lims)
- Deprecated repo is removed / made private
- Links are corrected so at least the legacy repo code runs as it did before it was replaced

**Comment by thobalose** [comment]
@dnk8n This repository was updated to reflect the above mentioned yesterday.

Kindly check and let me know...
